---
- name: Create a directory if it does not exist
  file:
    path: ~/.dwm
    state: directory
    mode: '0755'

- name: Copy dwm config files to ~/.dwm/
  command: cp -r {{ role_path }}/files/{{ item }} ~/.dwm
  with_items:
   - "autostart.sh"
