- name: Yay - Install dwm
  become: true
  yay:
    name: dwm

- name: Setup dwm - Checkout the custom branch
  git:
    repo: "https://github.com/C0USTEAU/dwm"
    dest: /tmp/dwm
    version: 6.2-fe-custom

- name: Setup dwm - make install the source
  become: true
  command: make install
  args:
    chdir: /tmp/dwm/

- name: Setup dwm - Remove the dwm download directory
  file:
    path: /tmp/dwm/
    state: absent
