- name: Install dwmblocks - Checkout the custom branch
  git:
    repo: "https://github.com/C0USTEAU/dwmblocks"
    dest: /tmp/dwmblocks
    version: fe-custom

- name: Install dwmblocks - make install the source
  become: true
  command: make install
  args:
    chdir: /tmp/dwmblocks/

- name: Install dwmblocks - Deploy dwmblocks scripts
  become: true
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: root
    mode: 0755
  with_fileglob:
    - /tmp/dwmblocks/scripts/*

- name: Install dwmblocks - Remove the dwmblocks download directory
  file:
    path: /tmp/dwmblocks/
    state: absent
