---
- name: Pacman - Upgrade all packages to the latest version
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

- name: Pacman - Install packages listed in group_vars/local.yml
  become: true
  pacman:
    name: "{{ packages }}"
