- name: Yay - Upgrade all packages to the latest version
  become: true
  yay:
    update_cache: yes
    upgrade: yes

- name: Yay - Install google-chrome
  become: true
  yay: name=google-chrome state=present

- name: Yay - Install dropbox
  become: true
  yay: name=dropbox state=present

- name: Yay - Install zoom
  become: true
  yay: name=zoom state=present

- name: Yay - Install mictray
  become: true
  yay: name=mictray state=present

