---
- name: Yay - Upgrade all packages to the latest version
  become: true
  yay:
    update_cache: yes
    upgrade: yes

- name: Yay - Install packages listed in group_vars/local.yml
  become: true
  yay:
    name: "{{ yay_packages }}"
    state: latest
