---
- name: Enable NetworkManager service
  become: true
  ansible.builtin.systemd:
    name: NetworkManager
    enabled: true
    masked: false

- name: Enable LightDM service
  become: true
  ansible.builtin.systemd:
    name: lightdm
    enabled: true
    masked: false

- name: Initial run of lux required
  become: true
  ansible.builtin.shell: lux

